# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_code', models.CharField(max_length=250)),
                ('event_cover', models.CharField(max_length=1000)),
                ('event_date', models.CharField(max_length=300)),
                ('event_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=200)),
                ('photo_source', models.CharField(max_length=1000)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Event')),
            ],
        ),
    ]
