# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_likes',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_share',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(default='pixlicode', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cover',
            field=models.CharField(default='defaultcover', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='pixli', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='wedding and tour', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='pixli_pic_caption', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Event'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='pixli_pic', max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_source',
            field=models.CharField(default='pixli_pic_url', max_length=1000),
        ),
    ]
