# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20160820_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_share',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
